import type { Completion } from "./contracts";
import { BRIDGE_VERSION, canonical, decimal, error, INTERNAL_HOST, json, now, readJson, sha256 } from "./contracts";

type Alias = { alias: string; upstream_model: string; status: string };
type Account = { id: string; name: string; platform: string; type: string; max_concurrency: number; credential_envelope: string; extra_json: string };
const bridge = (request: Request) => request.headers.get("X-Sub2API-Bridge-Version") === BRIDGE_VERSION;
const positive = (value: unknown): value is string => !!decimal(value) && value !== "0";
const safeJson = (value: unknown, fallback: unknown = {}) => { try { return JSON.parse(String(value)); } catch { return fallback; } };

export async function controlPlane(request: Request, env: Env): Promise<Response> {
  if (new URL(request.url).hostname !== INTERNAL_HOST || !bridge(request) || request.method !== "POST") return error("NOT_FOUND", 404);
  switch (new URL(request.url).pathname) { case "/v1/auth/resolve": return resolve(request, env); case "/v1/auth/touch": return touch(request, env); case "/v1/requests/admit": return admit(request, env); case "/v1/leases/renew": return lease(request, env, "/renew"); case "/v1/leases/release": return lease(request, env, "/release"); case "/v1/requests/complete": return complete(request, env); default: return error("NOT_FOUND", 404); }
}
async function authRow(hash: string, env: Env): Promise<Record<string, unknown> | null> { return env.DB.prepare("SELECT k.id key_id,k.user_id,k.group_id,k.name key_name,k.status key_status,k.ip_whitelist_json,k.ip_blacklist_json,k.expires_at,u.id user_id,u.status user_status,u.role,u.concurrency,u.balance_microusd,u.allowed_group_ids_json,u.restrict_public_groups,g.id group_id2,g.name group_name,g.platform,g.status group_status,g.is_exclusive,g.subscription_type FROM api_keys k JOIN users u ON u.id=k.user_id LEFT JOIN groups g ON g.id=k.group_id WHERE k.key_hash=?").bind(hash).first<Record<string, unknown>>(); }
function permitted(row: Record<string, unknown>, group?: string): boolean { return row.key_status === "active" && row.user_status === "active" && row.group_status === "active" && positive(row.key_id) && positive(row.user_id) && positive(row.group_id) && (!group || row.group_id === group) && BigInt(String(row.balance_microusd)) > 0n; }
async function resolve(request: Request, env: Env): Promise<Response> { const body = await readJson<{ key?: string }>(request); if (!body?.key) return error("API_KEY_NOT_FOUND", 404); const row = await authRow(await sha256(body.key), env); if (!row || !permitted(row)) return error("API_KEY_NOT_FOUND", 404); return json({ api_key: { id: row.key_id, user_id: row.user_id, name: row.key_name, status: row.key_status, group_id: row.group_id, ip_whitelist: safeJson(row.ip_whitelist_json, []), ip_blacklist: safeJson(row.ip_blacklist_json, []), expires_at: row.expires_at }, user: { id: row.user_id, status: row.user_status, role: row.role, concurrency: row.concurrency, balance_positive: true, allowed_group_ids: safeJson(row.allowed_group_ids_json, []), restrict_public_groups: Boolean(row.restrict_public_groups) }, group: { id: row.group_id2, name: row.group_name, platform: row.platform, status: row.group_status, is_exclusive: Boolean(row.is_exclusive), subscription_type: row.subscription_type } }); }
async function touch(request: Request, env: Env): Promise<Response> { const body = await readJson<{ api_key_id?: string; used_at?: string }>(request); if (!body || !positive(body.api_key_id) || !body.used_at) return error("INVALID_REQUEST"); await env.DB.prepare("UPDATE api_keys SET last_used_at=? WHERE id=?").bind(body.used_at, body.api_key_id).run(); return new Response(null, { status: 204 }); }
async function alias(model: string, env: Env): Promise<Alias | null> { try { const cached = await env.CONFIG_CACHE.get<Alias>(`model:${model}`, "json"); if (cached?.status === "active") return cached; } catch { /* cache never grants authority */ } const row = await env.DB.prepare("SELECT alias,upstream_model,status FROM model_aliases WHERE alias=?").bind(model).first<Alias>(); if (row?.status === "active") { try { await env.CONFIG_CACHE.put(`model:${model}`, JSON.stringify(row), { expirationTtl: 300 }); } catch { /* D1 is sufficient */ } return row; } return null; }
async function credentials(envelope: string, env: Env): Promise<Record<string, unknown> | null> { const runtime = env as Env & { ENVIRONMENT: string; ALLOW_TEST_FIXTURE: string; CREDENTIAL_ENCRYPTION_KEY?: string }; if (String(runtime.ENVIRONMENT) === "local" && String(runtime.ALLOW_TEST_FIXTURE) === "true" && envelope === "fixture:v1:mock-upstream") return { api_key: "fixture-upstream-token", base_url: "https://mock.upstream" }; if (!runtime.CREDENTIAL_ENCRYPTION_KEY || !envelope.startsWith("aes-gcm:v1:")) return null; try { const [, , iv, ciphertext] = envelope.split(":"); const key = await crypto.subtle.importKey("raw", Uint8Array.from(atob(runtime.CREDENTIAL_ENCRYPTION_KEY), x => x.charCodeAt(0)), "AES-GCM", false, ["decrypt"]); return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: Uint8Array.from(atob(iv), x => x.charCodeAt(0)) }, key, Uint8Array.from(atob(ciphertext), x => x.charCodeAt(0))))); } catch { return null; } }
async function admit(request: Request, env: Env): Promise<Response> {
  const body = await readJson<{ request_id?: string; api_key_id?: string; group_id?: string; model?: string; lease_ttl_seconds?: number }>(request); const owner = request.headers.get("X-Sub2API-Container-Id");
  if (!body?.request_id || !positive(body.api_key_id) || !positive(body.group_id) || !body.model || !owner || !Number.isInteger(body.lease_ttl_seconds)) return error("ADMISSION_REJECTED", 429);
  const auth = await env.DB.prepare("SELECT k.id key_id,k.user_id user_id,k.group_id,k.status key_status,u.status user_status,u.balance_microusd,g.status group_status FROM api_keys k JOIN users u ON u.id=k.user_id JOIN groups g ON g.id=k.group_id WHERE k.id=?").bind(body.api_key_id).first<Record<string, unknown>>(); if (!auth || !permitted(auth, body.group_id)) return error("ADMISSION_REJECTED", 429);
  const mapped = await alias(body.model, env); const account = mapped ? await env.DB.prepare("SELECT a.id,a.name,a.platform,a.type,a.max_concurrency,a.credential_envelope,a.extra_json FROM accounts a JOIN account_groups ag ON ag.account_id=a.id WHERE ag.group_id=? AND a.status='active' AND a.schedulable=1 AND a.platform='openai' AND a.type='apikey' ORDER BY a.priority DESC,a.id ASC LIMIT 1").bind(body.group_id).first<Account>() : null; if (!account) return error("ADMISSION_REJECTED", 429);
  const credential = await credentials(account.credential_envelope, env); if (!credential) return error("ADMISSION_REJECTED", 429);
  const stub = env.ACCOUNT_LEASE.get(env.ACCOUNT_LEASE.idFromName(`account:${account.id}`)); const acquired = await stub.fetch("https://lease/acquire", { method: "POST", body: JSON.stringify({ account_id: account.id, request_id: body.request_id, owner, max_concurrency: account.max_concurrency, ttl_seconds: body.lease_ttl_seconds }) }); if (!acquired.ok) return error("ADMISSION_REJECTED", 429); const leased = await acquired.json<{ lease: Record<string, string>; created: boolean }>();
  const inserted = await env.DB.prepare("INSERT OR IGNORE INTO gateway_requests(request_id,api_key_id,account_id,lease_id,lease_epoch,model,upstream_model,state,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(body.request_id, body.api_key_id, account.id, leased.lease.lease_id, leased.lease.epoch, body.model, mapped!.upstream_model, "admitted", now()).run();
  if (!inserted.meta.changes && leased.created) await stub.fetch("https://lease/release", { method: "POST", body: JSON.stringify(leased.lease) });
  if (!inserted.meta.changes) { const existing = await env.DB.prepare("SELECT account_id,lease_id,lease_epoch FROM gateway_requests WHERE request_id=? AND api_key_id=?").bind(body.request_id, body.api_key_id).first<Record<string, string>>(); if (!existing || existing.account_id !== account.id || existing.lease_id !== leased.lease.lease_id || existing.lease_epoch !== leased.lease.epoch) return error("ADMISSION_REJECTED", 429); }
  return json({ account: { id: account.id, name: account.name, platform: account.platform, type: account.type, concurrency: account.max_concurrency, credentials: credential, extra: safeJson(account.extra_json) }, upstream_model: mapped!.upstream_model, lease: leased.lease });
}
async function lease(request: Request, env: Env, path: string): Promise<Response> { const data = await readJson<Record<string, string | number>>(request); const owner = request.headers.get("X-Sub2API-Container-Id"); if (!data || !positive(data.account_id) || !owner || data.owner !== owner) return error("LEASE_IDENTITY_REJECTED", 409); return env.ACCOUNT_LEASE.get(env.ACCOUNT_LEASE.idFromName(`account:${data.account_id}`)).fetch(`https://lease${path}`, { method: "POST", body: JSON.stringify(data) }); }
function validCompletion(body: Completion | null): body is Completion { return !!body && body.schema_version === BRIDGE_VERSION && body.event_type === "gateway.usage.v1" && !!body.event_id && [body.request_id, body.api_key_id, body.account_id, body.lease_id, body.lease_epoch, body.input_tokens, body.output_tokens, body.cache_read_tokens, body.duration_ms].every(positive) && ["succeeded", "failed"].includes(body.outcome) && ["confirmed", "unknown"].includes(body.usage_state) && !!body.model && !!body.upstream_model; }
async function complete(request: Request, env: Env): Promise<Response> { const body = await readJson<Completion>(request); if (!validCompletion(body)) return error("INVALID_REQUEST"); const payload = canonical(body); const hash = await sha256(payload); const prior = await env.DB.prepare("SELECT payload_hash FROM outbox_events WHERE event_id=?").bind(body.event_id).first<{ payload_hash: string }>(); if (prior) return prior.payload_hash === hash ? new Response(null, { status: 204 }) : error("EVENT_CONFLICT", 409); const update = env.DB.prepare("UPDATE gateway_requests SET state=?,event_id=?,completed_at=? WHERE request_id=? AND api_key_id=? AND account_id=? AND lease_id=? AND lease_epoch=? AND state='admitted'").bind(body.outcome, body.event_id, now(), body.request_id, body.api_key_id, body.account_id, body.lease_id, body.lease_epoch); const outbox = env.DB.prepare("INSERT INTO outbox_events(event_id,request_id,payload_json,payload_hash,state,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM gateway_requests WHERE request_id=? AND event_id=?)").bind(body.event_id, body.request_id, payload, hash, "pending", now(), body.request_id, body.event_id); const result = await env.DB.batch([update, outbox]); if (result[0].meta.changes !== 1 || result[1].meta.changes !== 1) return error("REQUEST_IDENTITY_MISMATCH", 409); try { await publish(env, body.event_id, payload, hash); } catch { /* pending row is recovery source */ } return new Response(null, { status: 204 }); }
export async function publish(env: Env, eventId: string, payload: string, hash: string): Promise<void> { await env.USAGE_QUEUE.send({ event_id: eventId, payload, payload_hash: hash }); await env.DB.prepare("UPDATE outbox_events SET state='published',published_at=? WHERE event_id=? AND payload_hash=?").bind(now(), eventId, hash).run(); }
