import { DurableObject } from "cloudflare:workers";
import { decimal, error, json, readJson } from "./contracts";

type Lease = { account_id: string; lease_id: string; request_id: string; owner: string; epoch: string; expires_at: number };
type Acquire = { account_id: string; request_id: string; owner: string; max_concurrency: number; ttl_seconds: number };

/** One SQLite-backed business DO per decimal account ID. */
export class AccountLeaseDO extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) { super(ctx, env); ctx.storage.sql.exec("CREATE TABLE IF NOT EXISTS leases (lease_id TEXT PRIMARY KEY, account_id TEXT NOT NULL, request_id TEXT NOT NULL UNIQUE, owner TEXT NOT NULL, epoch INTEGER NOT NULL, expires_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS lease_state (key TEXT PRIMARY KEY, value INTEGER NOT NULL); INSERT OR IGNORE INTO lease_state VALUES ('epoch',0)"); }
  async fetch(request: Request): Promise<Response> { const data = await readJson<Record<string, unknown>>(request); if (!data) return error("INVALID_REQUEST"); const path = new URL(request.url).pathname; if (path === "/acquire") return this.acquire(data as unknown as Acquire); if (path === "/renew") return this.renew(data); if (path === "/release") return this.release(data); return error("NOT_FOUND", 404); }
  private valid(data: Record<string, unknown>): data is Record<string, string> { return ["account_id", "request_id", "lease_id", "owner", "epoch"].every((key) => typeof data[key] === "string" && data[key].length > 0) && !!decimal(data.account_id) && !!decimal(data.epoch); }
  private earliest(): number | null { return this.ctx.storage.sql.exec<{ expires_at: number }>("SELECT expires_at FROM leases ORDER BY expires_at LIMIT 1").toArray()[0]?.expires_at ?? null; }
  private async reschedule(time: number | null): Promise<void> { if (time === null) await this.ctx.storage.deleteAlarm(); else await this.ctx.storage.setAlarm(time); }
  private wire(lease: Lease, created: boolean) { return { lease: { lease_id: lease.lease_id, account_id: lease.account_id, request_id: lease.request_id, owner: lease.owner, epoch: lease.epoch, expires_at: new Date(lease.expires_at).toISOString() }, created }; }
  private async acquire(data: Acquire): Promise<Response> {
    if (!decimal(data.account_id) || !data.request_id || !data.owner || !Number.isInteger(data.max_concurrency) || data.max_concurrency < 1 || !Number.isInteger(data.ttl_seconds) || data.ttl_seconds < 3) return error("INVALID_REQUEST");
    let result: Lease | null = null; let created = false; let earliest: number | null = null;
    this.ctx.storage.transactionSync(() => { const time = Date.now(); this.ctx.storage.sql.exec("DELETE FROM leases WHERE expires_at<=?", time); const existing = this.ctx.storage.sql.exec<Lease>("SELECT account_id,lease_id,request_id,owner,CAST(epoch AS TEXT) epoch,expires_at FROM leases WHERE request_id=?", data.request_id).toArray()[0]; if (existing) { if (existing.account_id === data.account_id && existing.owner === data.owner) result = existing; earliest = this.earliest(); return; } if (this.ctx.storage.sql.exec<{ count: number }>("SELECT count(*) count FROM leases").one().count >= data.max_concurrency) { earliest = this.earliest(); return; } this.ctx.storage.sql.exec("UPDATE lease_state SET value=value+1 WHERE key='epoch'"); const epoch = this.ctx.storage.sql.exec<{ value: number }>("SELECT value FROM lease_state WHERE key='epoch'").one().value; result = { account_id: data.account_id, lease_id: crypto.randomUUID(), request_id: data.request_id, owner: data.owner, epoch: String(epoch), expires_at: time + data.ttl_seconds * 1000 }; this.ctx.storage.sql.exec("INSERT INTO leases VALUES(?,?,?,?,?,?)", result.lease_id, result.account_id, result.request_id, result.owner, epoch, result.expires_at); created = true; earliest = this.earliest(); });
    if (!result) return error("LEASE_UNAVAILABLE", 429); await this.reschedule(earliest); return json(this.wire(result, created));
  }
  private find(data: Record<string, unknown>): Lease | null { return this.ctx.storage.sql.exec<Lease>("SELECT account_id,lease_id,request_id,owner,CAST(epoch AS TEXT) epoch,expires_at FROM leases WHERE account_id=? AND request_id=? AND lease_id=? AND owner=? AND epoch=?", data.account_id, data.request_id, data.lease_id, data.owner, data.epoch).toArray()[0] ?? null; }
  private async renew(data: Record<string, unknown>): Promise<Response> { const ttl = Number(data.ttl_seconds); if (!this.valid(data) || !Number.isInteger(ttl) || ttl < 3) return error("LEASE_IDENTITY_REJECTED", 409); let result: Lease | null = null; let earliest: number | null = null; this.ctx.storage.transactionSync(() => { this.ctx.storage.sql.exec("DELETE FROM leases WHERE expires_at<=?", Date.now()); result = this.find(data); if (result) { result.expires_at = Date.now() + ttl * 1000; this.ctx.storage.sql.exec("UPDATE leases SET expires_at=? WHERE lease_id=?", result.expires_at, result.lease_id); } earliest = this.earliest(); }); if (!result) return error("LEASE_IDENTITY_REJECTED", 409); await this.reschedule(earliest); return json(this.wire(result, false)); }
  private async release(data: Record<string, unknown>): Promise<Response> { if (!this.valid(data)) return error("LEASE_IDENTITY_REJECTED", 409); let released = false; let earliest: number | null = null; this.ctx.storage.transactionSync(() => { this.ctx.storage.sql.exec("DELETE FROM leases WHERE expires_at<=?", Date.now()); const found = this.find(data); if (found) { this.ctx.storage.sql.exec("DELETE FROM leases WHERE lease_id=?", found.lease_id); released = true; } earliest = this.earliest(); }); await this.reschedule(earliest); return json({ released }); }
  async alarm(): Promise<void> { let earliest: number | null = null; this.ctx.storage.transactionSync(() => { this.ctx.storage.sql.exec("DELETE FROM leases WHERE expires_at<=?", Date.now()); earliest = this.earliest(); }); await this.reschedule(earliest); }
}
