-- Decimal TEXT IDs and fixed-point microusd TEXT values protect every JS/D1 boundary.
CREATE TABLE users (id TEXT PRIMARY KEY CHECK(id GLOB '[0-9]*'), status TEXT NOT NULL CHECK(status IN ('active','disabled')), role TEXT NOT NULL, concurrency INTEGER NOT NULL CHECK(concurrency >= 1), balance_microusd TEXT NOT NULL CHECK(balance_microusd GLOB '[0-9]*'), allowed_group_ids_json TEXT NOT NULL DEFAULT '[]', restrict_public_groups INTEGER NOT NULL DEFAULT 0 CHECK(restrict_public_groups IN (0,1)), created_at TEXT NOT NULL);
CREATE TABLE groups (id TEXT PRIMARY KEY CHECK(id GLOB '[0-9]*'), name TEXT NOT NULL, platform TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','disabled')), is_exclusive INTEGER NOT NULL DEFAULT 0 CHECK(is_exclusive IN (0,1)), subscription_type TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE api_keys (id TEXT PRIMARY KEY CHECK(id GLOB '[0-9]*'), user_id TEXT NOT NULL REFERENCES users(id), group_id TEXT REFERENCES groups(id), name TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','disabled')), key_hash TEXT NOT NULL UNIQUE CHECK(length(key_hash)=64), ip_whitelist_json TEXT NOT NULL DEFAULT '[]', ip_blacklist_json TEXT NOT NULL DEFAULT '[]', expires_at TEXT, last_used_at TEXT, created_at TEXT NOT NULL);
CREATE INDEX api_keys_lookup_idx ON api_keys(key_hash, status);
CREATE TABLE accounts (id TEXT PRIMARY KEY CHECK(id GLOB '[0-9]*'), name TEXT NOT NULL, platform TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','disabled')), schedulable INTEGER NOT NULL CHECK(schedulable IN (0,1)), priority INTEGER NOT NULL DEFAULT 0, max_concurrency INTEGER NOT NULL CHECK(max_concurrency >= 1), credential_envelope TEXT NOT NULL, extra_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE account_groups (account_id TEXT NOT NULL REFERENCES accounts(id), group_id TEXT NOT NULL REFERENCES groups(id), PRIMARY KEY(account_id, group_id));
CREATE INDEX account_group_schedule_idx ON account_groups(group_id, account_id);
CREATE TABLE model_aliases (alias TEXT PRIMARY KEY, upstream_model TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','disabled')), updated_at TEXT NOT NULL);
CREATE TABLE gateway_requests (request_id TEXT PRIMARY KEY, api_key_id TEXT NOT NULL REFERENCES api_keys(id), account_id TEXT NOT NULL REFERENCES accounts(id), lease_id TEXT NOT NULL, lease_epoch TEXT NOT NULL, model TEXT NOT NULL, upstream_model TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('admitted','succeeded','failed')), event_id TEXT UNIQUE, completed_at TEXT, created_at TEXT NOT NULL);
CREATE INDEX gateway_requests_account_state_idx ON gateway_requests(account_id, state);
CREATE TABLE outbox_events (event_id TEXT PRIMARY KEY, request_id TEXT NOT NULL REFERENCES gateway_requests(request_id), payload_json TEXT NOT NULL, payload_hash TEXT NOT NULL CHECK(length(payload_hash)=64), state TEXT NOT NULL CHECK(state IN ('pending','published')), published_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE usage_events (event_id TEXT PRIMARY KEY, request_id TEXT NOT NULL, payload_hash TEXT NOT NULL CHECK(length(payload_hash)=64), api_key_id TEXT NOT NULL, account_id TEXT NOT NULL, input_tokens TEXT NOT NULL CHECK(input_tokens GLOB '[0-9]*'), output_tokens TEXT NOT NULL CHECK(output_tokens GLOB '[0-9]*'), cache_read_tokens TEXT NOT NULL CHECK(cache_read_tokens GLOB '[0-9]*'), created_at TEXT NOT NULL);
